name: Compile VIM4 DTB Only

on: 
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build-dtb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler

      - name: Compile
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make defconfig
          # 注意：这里的文件名必须和你仓库里实际的文件名一致
          make amlogic/amlogic-t7-a311d2-khadas-vim4.dtb

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: VIM4-Custom-DTB
          path: arch/arm64/boot/dts/amlogic/amlogic-t7-a311d2-khadas-vim4.dtb
